server:
  address: 0.0.0.0
  port: 9000

spring:
  application:
    name: givenget-auth
  data:
    mongodb:
      uri: mongodb://localhost:27017/givenget
  security:
    oauth2:
      authorizationserver:
        client:
          givenget:
            registration:
              client-id: givenget
              client-secret: "{noop}SuperSecret"
              client-authentication-methods:
                - client_secret_post
              authorization-grant-types:
                - client_credentials
              scopes:
                - givenget:read
                - givenget:write
